apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: app-auto
  namespace: web
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: app-repo
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: './'
    strategy: Setters
