apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: app-policy
  namespace: web
spec:
  imageRepositoryRef:
    name: app-image
  filterTags:
    pattern: '^(?P<timestamp>.*)'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc
